// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGH5U-ffkkVWKIxSYnwpzwAy8MKtw-8Nc',
    appId: '1:75031439221:web:26dbeee0f503c747ad153c',
    messagingSenderId: '75031439221',
    projectId: 'project2-61871',
    authDomain: 'project2-61871.firebaseapp.com',
    storageBucket: 'project2-61871.firebasestorage.app',
    measurementId: 'G-WKFP675JJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLX6YKtNxmht3MznnUFUKYuSOfI8RSrCE',
    appId: '1:75031439221:android:c6d13d84c3bd4075ad153c',
    messagingSenderId: '75031439221',
    projectId: 'project2-61871',
    storageBucket: 'project2-61871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsTbnKrCSiT7g4-3ufu1eCModu7LAo96s',
    appId: '1:75031439221:ios:82fa55a108c93956ad153c',
    messagingSenderId: '75031439221',
    projectId: 'project2-61871',
    storageBucket: 'project2-61871.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsTbnKrCSiT7g4-3ufu1eCModu7LAo96s',
    appId: '1:75031439221:ios:82fa55a108c93956ad153c',
    messagingSenderId: '75031439221',
    projectId: 'project2-61871',
    storageBucket: 'project2-61871.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGH5U-ffkkVWKIxSYnwpzwAy8MKtw-8Nc',
    appId: '1:75031439221:web:cdb4082969ea77eaad153c',
    messagingSenderId: '75031439221',
    projectId: 'project2-61871',
    authDomain: 'project2-61871.firebaseapp.com',
    storageBucket: 'project2-61871.firebasestorage.app',
    measurementId: 'G-R17T9KZLLE',
  );
}
